### ISSUE TITLE
Use mutt alias format

### ISSUE THREAD

**Issue by cristianpb** [Konfekt/mutt-alias.sh#2]
Hi Enno !
Nice job, I wanted to populate my alias file with the received mails and your script it's a good starting point.

As stated in the line https://github.com/Konfekt/mutt-alias.sh/blob/master/mutt-alias.sh#L124 , your script produces the following pattern:
`alias foo@bar.com foo@bar.com`

However mutt format is:
`alias <nickname> [ <long name> ] <address>`

What do you think of changing the script a little bit in order to take mutt format into account ?

**Comment by Konfekt** [comment]
Hello! Thanks, this is an adaption of https://gitlab.com/protist/mutt-vid. 

To  build `<nickname>`, the  long name is too ambiguous. Therefore, it simply uses the e-mail address, which alas has the advantage of being unique.

If you want to preserve the long name, then

https://github.com/Konfekt/mutt-alias.sh/blob/9f648b14010ea89098c66e23eb0991dda5a3bed8/mutt-alias.sh#L112

there could be added something like

```sh
out_name="$( <<<"$each_to" sed --regexp-extended 's/^To:\s*([^<])*<.*>$/\1/' )"
```

and https://github.com/Konfekt/mutt-alias.sh/blob/9f648b14010ea89098c66e23eb0991dda5a3bed8/mutt-alias.sh#L124 changed to

```sh          
new_entry="alias ${out_to} $outname ${out_to} # mutt-alias: e-mail sent on ${hr_out_date}"
```

**Comment by cristianpb** [comment]
Thank you, I've done something similar.

In addition I have to:
* add `bash` to the shebang because I had bad parsing results for the regex using `sh`
* add the `TMPDIR` variable because it's not defined in the script

**Comment by Konfekt** [comment]
> - add bash to the shebang because I had bad parsing results for the regex using 
    - add the TMPDIR variable because it's not defined in the script

The latest commit should make this shell script more portable.

My suggestions to add a name did not work out well. On top, there is the difficulty of MIME-encoded characters; perhaps they are best skipped instead of introducing. Perhaps you could leave your solution here or as a pull request for future reference.

**Comment by Konfekt** [comment]
I guess we can close this. Give the mime decoding a try and tell me how it works out for you.
